[package]
name = "_"
version = "0.0.2"
edition = "2021"
repository = "https://github.com/haoxins/qomo"

[lib]
name = "qomo"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21"
qomo = { path = "../core" }
